/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Org extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.OrgRecord> {

	private static final long serialVersionUID = -1803085885;

	/**
	 * The singleton instance of <code>georgia.org</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Org ORG = new org.chris_martin.georgia.jooq.georgia.tables.Org();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.OrgRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.OrgRecord.class;
	}

	/**
	 * The column <code>georgia.org.id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.org.title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>georgia.org</code> table reference
	 */
	public Org() {
		super("org", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.org</code> table reference
	 */
	public Org(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.Org.ORG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.Org as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.Org(alias);
	}
}
