/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Orgs extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord> {

	private static final long serialVersionUID = -1270514450;

	/**
	 * The singleton instance of <code>georgia.orgs</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Orgs ORGS = new org.chris_martin.georgia.jooq.georgia.tables.Orgs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord.class;
	}

	/**
	 * The column <code>georgia.orgs.id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The column <code>georgia.orgs.title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The column <code>georgia.orgs.org_type_id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord, java.lang.String> ORG_TYPE_ID = createField("org_type_id", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The column <code>georgia.orgs.year</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord, java.lang.Short> YEAR = createField("year", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * Create a <code>georgia.orgs</code> table reference
	 */
	public Orgs() {
		super("orgs", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.orgs</code> table reference
	 */
	public Orgs(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.Orgs as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.Orgs(alias);
	}
}
