/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class OrgType extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypeRecord> {

	private static final long serialVersionUID = 2031595127;

	/**
	 * The singleton instance of <code>georgia.org_type</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.OrgType ORG_TYPE = new org.chris_martin.georgia.jooq.georgia.tables.OrgType();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypeRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypeRecord.class;
	}

	/**
	 * The column <code>georgia.org_type.id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypeRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.org_type.title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypeRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>georgia.org_type</code> table reference
	 */
	public OrgType() {
		super("org_type", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.org_type</code> table reference
	 */
	public OrgType(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.OrgType.ORG_TYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.OrgType as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.OrgType(alias);
	}
}
