/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class OrgTypes extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypesRecord> {

	private static final long serialVersionUID = -1424541842;

	/**
	 * The singleton instance of <code>georgia.org_types</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.OrgTypes ORG_TYPES = new org.chris_martin.georgia.jooq.georgia.tables.OrgTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypesRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypesRecord.class;
	}

	/**
	 * The column <code>georgia.org_types.id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypesRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.org_types.title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.OrgTypesRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>georgia.org_types</code> table reference
	 */
	public OrgTypes() {
		super("org_types", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.org_types</code> table reference
	 */
	public OrgTypes(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.OrgTypes.ORG_TYPES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.OrgTypes as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.OrgTypes(alias);
	}
}
