/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Payments extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord> {

	private static final long serialVersionUID = -641948105;

	/**
	 * The singleton instance of <code>georgia.payments</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Payments PAYMENTS = new org.chris_martin.georgia.jooq.georgia.tables.Payments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord.class;
	}

	/**
	 * The column <code>georgia.payments.person_name</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord, java.lang.String> PERSON_NAME = createField("person_name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.payments.job_title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord, java.lang.String> JOB_TITLE = createField("job_title", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.payments.salary</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord, java.math.BigDecimal> SALARY = createField("salary", org.jooq.impl.SQLDataType.NUMERIC.precision(11, 2), this);

	/**
	 * The column <code>georgia.payments.travel</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord, java.math.BigDecimal> TRAVEL = createField("travel", org.jooq.impl.SQLDataType.NUMERIC.precision(11, 2), this);

	/**
	 * The column <code>georgia.payments.org_id</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord, java.lang.String> ORG_ID = createField("org_id", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>georgia.payments</code> table reference
	 */
	public Payments() {
		super("payments", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.payments</code> table reference
	 */
	public Payments(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.Payments as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.Payments(alias);
	}
}
