/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class People extends org.jooq.impl.TableImpl<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord> {

	private static final long serialVersionUID = -1395485268;

	/**
	 * The singleton instance of <code>georgia.people</code>
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.People PEOPLE = new org.chris_martin.georgia.jooq.georgia.tables.People();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord> getRecordType() {
		return org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord.class;
	}

	/**
	 * The column <code>georgia.people.person_name</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord, java.lang.String> PERSON_NAME = createField("person_name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.people.job_title</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord, java.lang.String> JOB_TITLE = createField("job_title", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>georgia.people.salary</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord, java.math.BigDecimal> SALARY = createField("salary", org.jooq.impl.SQLDataType.NUMERIC.precision(11, 2), this);

	/**
	 * The column <code>georgia.people.travel</code>. 
	 */
	public final org.jooq.TableField<org.chris_martin.georgia.jooq.georgia.tables.records.PeopleRecord, java.math.BigDecimal> TRAVEL = createField("travel", org.jooq.impl.SQLDataType.NUMERIC.precision(11, 2), this);

	/**
	 * Create a <code>georgia.people</code> table reference
	 */
	public People() {
		super("people", org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA);
	}

	/**
	 * Create an aliased <code>georgia.people</code> table reference
	 */
	public People(java.lang.String alias) {
		super(alias, org.chris_martin.georgia.jooq.georgia.Georgia.GEORGIA, org.chris_martin.georgia.jooq.georgia.tables.People.PEOPLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.chris_martin.georgia.jooq.georgia.tables.People as(java.lang.String alias) {
		return new org.chris_martin.georgia.jooq.georgia.tables.People(alias);
	}
}
