/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.information_schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class InformationSchema extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -36494047;

	/**
	 * The singleton instance of <code>information_schema</code>
	 */
	public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

	/**
	 * No further instances allowed
	 */
	private InformationSchema() {
		super("information_schema");
	}
}
