/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.pg_temp_1;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PgTemp_1 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 472842717;

	/**
	 * The singleton instance of <code>pg_temp_1</code>
	 */
	public static final PgTemp_1 PG_TEMP_1 = new PgTemp_1();

	/**
	 * No further instances allowed
	 */
	private PgTemp_1() {
		super("pg_temp_1");
	}
}
