/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.pg_toast_temp_1;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PgToastTemp_1 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1665864953;

	/**
	 * The singleton instance of <code>pg_toast_temp_1</code>
	 */
	public static final PgToastTemp_1 PG_TOAST_TEMP_1 = new PgToastTemp_1();

	/**
	 * No further instances allowed
	 */
	private PgToastTemp_1() {
		super("pg_toast_temp_1");
	}
}
