/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.pg_catalog;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PgCatalog extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -2142445369;

	/**
	 * The singleton instance of <code>pg_catalog</code>
	 */
	public static final PgCatalog PG_CATALOG = new PgCatalog();

	/**
	 * No further instances allowed
	 */
	private PgCatalog() {
		super("pg_catalog");
	}
}
