/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.pg_toast;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PgToast extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1513742869;

	/**
	 * The singleton instance of <code>pg_toast</code>
	 */
	public static final PgToast PG_TOAST = new PgToast();

	/**
	 * No further instances allowed
	 */
	private PgToast() {
		super("pg_toast");
	}
}
