/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class OrgsRecord extends org.jooq.impl.TableRecordImpl<org.chris_martin.georgia.jooq.georgia.tables.records.OrgsRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.lang.Short> {

	private static final long serialVersionUID = 278941811;

	/**
	 * Setter for <code>georgia.orgs.id</code>. 
	 */
	public void setId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>georgia.orgs.id</code>. 
	 */
	public java.lang.String getId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>georgia.orgs.title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>georgia.orgs.title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>georgia.orgs.org_type_id</code>. 
	 */
	public void setOrgTypeId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>georgia.orgs.org_type_id</code>. 
	 */
	public java.lang.String getOrgTypeId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>georgia.orgs.year</code>. 
	 */
	public void setYear(java.lang.Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>georgia.orgs.year</code>. 
	 */
	public java.lang.Short getYear() {
		return (java.lang.Short) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.Short> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.Short> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS.ORG_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field4() {
		return org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOrgTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value4() {
		return getYear();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OrgsRecord
	 */
	public OrgsRecord() {
		super(org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS);
	}
}
