/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PaymentsRecord extends org.jooq.impl.TableRecordImpl<org.chris_martin.georgia.jooq.georgia.tables.records.PaymentsRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Short> {

	private static final long serialVersionUID = 1288090322;

	/**
	 * Setter for <code>georgia.payments.person_name</code>. 
	 */
	public void setPersonName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>georgia.payments.person_name</code>. 
	 */
	public java.lang.String getPersonName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>georgia.payments.job_title</code>. 
	 */
	public void setJobTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>georgia.payments.job_title</code>. 
	 */
	public java.lang.String getJobTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>georgia.payments.salary</code>. 
	 */
	public void setSalary(java.math.BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>georgia.payments.salary</code>. 
	 */
	public java.math.BigDecimal getSalary() {
		return (java.math.BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>georgia.payments.travel</code>. 
	 */
	public void setTravel(java.math.BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>georgia.payments.travel</code>. 
	 */
	public java.math.BigDecimal getTravel() {
		return (java.math.BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>georgia.payments.org_id</code>. 
	 */
	public void setOrgId(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>georgia.payments.org_id</code>. 
	 */
	public java.lang.String getOrgId() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>georgia.payments.year</code>. 
	 */
	public void setYear(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>georgia.payments.year</code>. 
	 */
	public java.lang.Short getYear() {
		return (java.lang.Short) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Short> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.math.BigDecimal, java.math.BigDecimal, java.lang.String, java.lang.Short> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.PERSON_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.JOB_TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field3() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.SALARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field4() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.TRAVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.ORG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS.YEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPersonName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getJobTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value3() {
		return getSalary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value4() {
		return getTravel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getOrgId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getYear();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PaymentsRecord
	 */
	public PaymentsRecord() {
		super(org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS);
	}
}
