/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Georgia extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 2145658555;

	/**
	 * The singleton instance of <code>georgia</code>
	 */
	public static final Georgia GEORGIA = new Georgia();

	/**
	 * No further instances allowed
	 */
	private Georgia() {
		super("georgia");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS,
			org.chris_martin.georgia.jooq.georgia.tables.OrgTypes.ORG_TYPES,
			org.chris_martin.georgia.jooq.georgia.tables.People.PEOPLE);
	}
}
