/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in georgia
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Tables {

	/**
	 * The table georgia.orgs
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Orgs ORGS = org.chris_martin.georgia.jooq.georgia.tables.Orgs.ORGS;

	/**
	 * The table georgia.org_types
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.OrgTypes ORG_TYPES = org.chris_martin.georgia.jooq.georgia.tables.OrgTypes.ORG_TYPES;

	/**
	 * The table georgia.payments
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Payments PAYMENTS = org.chris_martin.georgia.jooq.georgia.tables.Payments.PAYMENTS;
}
