/**
 * This class is generated by jOOQ
 */
package org.chris_martin.georgia.jooq.georgia;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in georgia
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Tables {

	/**
	 * The table georgia.org
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.Org ORG = org.chris_martin.georgia.jooq.georgia.tables.Org.ORG;

	/**
	 * The table georgia.org_type
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.OrgType ORG_TYPE = org.chris_martin.georgia.jooq.georgia.tables.OrgType.ORG_TYPE;

	/**
	 * The table georgia.people
	 */
	public static final org.chris_martin.georgia.jooq.georgia.tables.People PEOPLE = org.chris_martin.georgia.jooq.georgia.tables.People.PEOPLE;
}
